# Simulation settings
NUM_STEPS = 10000
INITIAL_PRICE = 100

# Agents settings
NUM_NOISE_TRADERS = 2
NUM_MARKET_MAKERS = 2
NUM_INFORMED_TRADERS = 4
NUM_FUNDAMENTAL_TRADERS = 5

# Trend trader settings
NUM_TREND_TRADERS = 2
TREND_TRADER_LOOKBACK = 20
TREND_TRADER_THRESHOLD = 0.05 #
TREND_TRADER_AGGRESSIVENESS = 3.0 #
TREND_TRADER_MAX_QTY = 5

NOISE_TRADER_NOISE_LEVEL = 0.3
INFORMED_TRADER_SENSITIVITY = 0.2
INFORMED_TRADER_AGGRESSIVENESS = 0.2
FUNDAMENTAL_TRADER_AGGRESSIVENESS = 0.1
FUNDAMENTAL_DRIFT = 0.0
FUNDAMENTAL_INTERVAL = 50
FUNDAMENTAL_SIGMA = 1

MM_BASE_SPREAD = 0.05
MM_INV_RISK = 0.01
MM_MAX_INVENTORY = 30
MM_BASE_SIZE = 3
MM_VOL_SENS = 0.4

# News settings
NEWS_PROBABILITY = 0.2
NEWS_VOLATILITY = 1.5
