# Simulation settings
NUM_STEPS = 2000
INITIAL_PRICE = 100

# Agents settings
NUM_NOISE_TRADERS = 3
NUM_MARKET_MAKERS = 2
NUM_INFORMED_TRADERS = 4
NUM_FUNDAMENTAL_TRADERS = 3

# Trend trader settings
NUM_TREND_TRADERS = 3
TREND_TRADER_LOOKBACK = 20
TREND_TRADER_THRESHOLD = 0.0001
TREND_TRADER_AGGRESSIVENESS = 0.0005
TREND_TRADER_MAX_QTY = 5

NOISE_TRADER_NOISE_LEVEL = 0.5
MARKET_MAKER_SPREAD = 0.05
INFORMED_TRADER_SENSITIVITY = 0.2
INFORMED_TRADER_AGGRESSIVENESS = 0.2
FUNDAMENTAL_TRADER_AGGRESSIVENESS = 0.1
FUNDAMENTAL_DRIFT = 0.0
FUNDAMENTAL_INTERVAL = 50
FUNDAMENTAL_SIGMA = 1

# News settings
NEWS_PROBABILITY = 0.2
NEWS_VOLATILITY = 1.5
